services:
  pg-service:
    container_name: scavenger-hunt
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: scavenger-hunt
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
